// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXL3ilirCKrif-_HS9CIa_ELr1avgQF8E',
    appId: '1:28641557685:web:7e6577449c7db9cb9f92fc',
    messagingSenderId: '28641557685',
    projectId: 'lenchat-fc7be',
    authDomain: 'lenchat-fc7be.firebaseapp.com',
    storageBucket: 'lenchat-fc7be.firebasestorage.app',
    measurementId: 'G-ZRM88WCDC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUu9mnGH9KJainY9jiL5Ksjp_jy6E6NA',
    appId: '1:28641557685:android:7ff22097603dece99f92fc',
    messagingSenderId: '28641557685',
    projectId: 'lenchat-fc7be',
    storageBucket: 'lenchat-fc7be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivNCDLvdnw32ebdynSTLV8MT1aMCsGMs',
    appId: '1:28641557685:ios:6d9a1f6d211b34d69f92fc',
    messagingSenderId: '28641557685',
    projectId: 'lenchat-fc7be',
    storageBucket: 'lenchat-fc7be.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCivNCDLvdnw32ebdynSTLV8MT1aMCsGMs',
    appId: '1:28641557685:ios:6d9a1f6d211b34d69f92fc',
    messagingSenderId: '28641557685',
    projectId: 'lenchat-fc7be',
    storageBucket: 'lenchat-fc7be.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXL3ilirCKrif-_HS9CIa_ELr1avgQF8E',
    appId: '1:28641557685:web:889dd5fb1fc379709f92fc',
    messagingSenderId: '28641557685',
    projectId: 'lenchat-fc7be',
    authDomain: 'lenchat-fc7be.firebaseapp.com',
    storageBucket: 'lenchat-fc7be.firebasestorage.app',
    measurementId: 'G-WB4NZX0L9S',
  );
}
